<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>HassanAdly.Infrastructure</RootNamespace>
    <AssemblyName>HassanAdly.Infrastructure</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Application\Application.csproj" />
  </ItemGroup>

</Project>
